-- MySQL Script generated by MySQL Workbench
-- Fri May 14 22:25:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livrariabg` DEFAULT CHARACTER SET utf8 ;
USE `livrariabg` ;

-- -----------------------------------------------------
-- Table `livrariabg`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cliente(
  idCliente INT NOT NULL AUTO_INCREMENT,
  nomeCliente VARCHAR(45) NOT NULL,
  cpfCliente VARCHAR(11) NOT NULL,
  emailCliente VARCHAR(45) NOT NULL,
  sexoCliente CHAR(1) NOT NULL,
  dataNascCliente DATETIME NOT NULL,
  statusCliente VARCHAR(45) NOT NULL,
  PRIMARY KEY (idCliente)
  );
/*INSERIR CLIENTE*/
 INSERT INTO CLIENTE(nomeCliente, cpfCliente, emailCliente, sexoCliente, dataNascCliente, statusCliente)
 VALUES
 ('HENRIQUE DA SILVA', '47231907718','henri@teste.com.br','M', STR_TO_DATE( '31/05/2014', '%d/%m/%Y' ), 'Ativo');

INSERT INTO CLIENTE(nomeCliente, cpfCliente, emailCliente, sexoCliente, dataNascCliente, statusCliente)
VALUES
('GUILHERME DA CRUZ','47137969909','guisz@teste.com.br','M',STR_TO_DATE( '15/02/2020', '%d/%m/%Y' ),'Ativo');

INSERT INTO CLIENTE(nomeCliente, cpfCliente, emailCliente, sexoCliente, dataNascCliente, statusCliente)
VALUES
('MARLI DE OLIVEIRA','49937813347','marl@teste.com.br','M',STR_TO_DATE( '05/07/1998', '%d/%m/%Y' ),'Ativo');

INSERT INTO CLIENTE(nomeCliente, cpfCliente, emailCliente, sexoCliente, dataNascCliente, statusCliente)
VALUES
('FERNANDA DE SOUZA','47329109816','ferzinha@teste.com.br','M',STR_TO_DATE( '05/07/1998', '%d/%m/%Y' ),'Ativo');

-- -----------------------------------------------------
-- Table `livrariabg`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS funcionario (
  idFunc INT NOT NULL AUTO_INCREMENT,
  nomeFunc VARCHAR(45) NOT NULL,
  cpfFunc VARCHAR(11) NOT NULL,
  emailFunc VARCHAR(45) NOT NULL,
  cargo VARCHAR(45) NOT NULL,
  senhaFunc VARCHAR(45) NOT NULL,
  nivelAcesso VARCHAR(15) NOT NULL,
  PRIMARY KEY (idFunc)
  );
 /*INSERIR FUNCIONARIO*/
INSERT INTO FUNCIONARIO (nomeFunc, cpfFunc, emailFunc, cargo, senhaFunc, nivelAcesso )
VALUES 
('Nilson Jose', '03958220035','nilson@gmail.com', 'Gerente geral','123456', 'Admin');
INSERT INTO FUNCIONARIO (nomeFunc, cpfFunc, emailFunc, cargo, senhaFunc, nivelAcesso )
VALUES 
('JOÃO ALMEIDA', '47329109816','joao@gmail.com','Analista de banco de dados','123456', 'Usuario');
INSERT INTO FUNCIONARIO (nomeFunc, cpfFunc, emailFunc, cargo, senhaFunc, nivelAcesso )
VALUES 
('MARIA DE OLIVEIRA', '45329103256','maria@gmail.com','Analista mobile','789654', 'Usuario');
INSERT INTO FUNCIONARIO (nomeFunc, cpfFunc, emailFunc, cargo, senhaFunc, nivelAcesso )
VALUES 
('CARLOS DA SILVA', '50029103789','carlos@gmail.com','Analista de sistema','658742', 'Usuario');
select * from funcionario;

-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS telefone (
  idTelefone INT NOT NULL AUTO_INCREMENT,
  idCliente INT NULL,
  idFunc INT NULL,
  TipoTelefone VARCHAR(45) NOT NULL,
  dddTelefone INT NULL,
  numeroTelefone INT NULL,
  PRIMARY KEY (idTelefone),
  FOREIGN KEY (idCliente) REFERENCES cliente (idCliente),
  FOREIGN KEY (idFunc) REFERENCES funcionario (idFunc)
 );
 select * from cliente;
 select * from funcionario;
 select * from telefone;
 
/* insert telefone cliente*/
INSERT INTO telefone(idCliente, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1,'Celular', 11, 958732495);
INSERT INTO telefone(idCliente, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1, 'Residencial', 11, 36905021);
INSERT INTO telefone(idCliente, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1, 'Comercial', 11, 58703526);

/* insert telefone funcionario*/
INSERT INTO telefone(idFunc, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1,'Celular', 11, 995362495);
INSERT INTO telefone(idFunc, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1, 'Residencial', 11, 58926395);
INSERT INTO telefone(idFunc, TipoTelefone, dddTelefone, numeroTelefone )
VALUES (1, 'Comercial', 11, 36119090);

-- -----------------------------------------------------
-- Table `livrariabg`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS endereco (
  idEndereco INT NOT NULL AUTO_INCREMENT,
  idCliente INT NULL,
  idFunc INT NULL,
  tipoEndereco VARCHAR(45) NOT NULL,
  logradouro VARCHAR(45) NOT NULL,
  numero INT NOT NULL,
  complemento VARCHAR(45) NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  CEP VARCHAR(9) NOT NULL,
  cidade varchar(100) NOT NULL,
  estado varchar(100) NOT NULL,
  UF char(2) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  FOREIGN KEY (idCliente) REFERENCES cliente (idCliente),
  FOREIGN KEY (idFunc) REFERENCES funcionario (idFunc)
  );
INSERT INTO endereco(idCliente, tipoEndereco, logradouro, numero, complemento, bairro, CEP, Cidade, estado, UF)
VALUES (1, 'residencial', 'Rua Tarira', 36, 'Casa 11', 'Jd do Santo','05842120','São Paulo','São Paulo','SP');
  
  select * from endereco
  inner join cliente on cliente.idCliente = endereco.idCliente;
-- -----------------------------------------------------
-- Table `livrariabg`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS editora (
  idEditora INT NOT NULL AUTO_INCREMENT,
  nomeEditora VARCHAR(100) NOT NULL,
  PRIMARY KEY (idEditora)
  );
/*INSERT EDITORA*/
INSERT INTO EDITORA(nomeEditora) VALUES ('INTRINSECA');
INSERT INTO EDITORA(nomeEditora) VALUES ('ARQUEIRO');
INSERT INTO EDITORA(nomeEditora) VALUES ('RECORD');
INSERT  INTO EDITORA(nomeEditora) VALUES ('SEXTANTE / GMT');
INSERT INTO EDITORA(nomeEditora) VALUES ('GENTE');
INSERT INTO EDITORA(nomeEditora) VALUES ('EDITORA NACIONAL');
INSERT INTO EDITORA(nomeEditora) VALUES ('CAMINHO SUAVE ED.');
INSERT INTO EDITORA(nomeEditora) VALUES ('ROCCO');
INSERT INTO EDITORA(nomeEditora) VALUES ('AGORA EDITORA');
INSERT INTO EDITORA(nomeEditora) VALUES ('COMPANHIA DAS LETRAS');
INSERT INTO EDITORA(nomeEditora) VALUES ('OBJETIVA');
INSERT INTO EDITORA(nomeEditora) VALUES ('BUZZ EDITORA');
INSERT INTO EDITORA(nomeEditora) VALUES ('RECORD');
INSERT INTO EDITORA(nomeEditora) VALUES ('GLOBO ART');
INSERT INTO EDITORA(nomeEditora) VALUES ('ALPH');
INSERT INTO EDITORA(nomeEditora) VALUES ('VALENTINA');
INSERT INTO EDITORA(nomeEditora) VALUES ('ARTMED'); 
INSERT INTO EDITORA(nomeEditora) VALUES ('FARO EDITORIAL');
INSERT INTO EDITORA(nomeEditora) VALUES ('BALÃO EDITORIAL');
INSERT INTO EDITORA(nomeEditora) VALUES ('BERTRAND BRASIL');
INSERT INTO EDITORA(nomeEditora) VALUES ('DAVID FINKING BOOKS');
INSERT INTO EDITORA(nomeEditora) VALUES ('SARAIVA');
INSERT INTO EDITORA(nomeEditora) VALUES ('MARTINS FONTES');

-- -----------------------------------------------------
-- Table `Livrariabg`.`formatolivro`
-- -----------------------------------------------------
create table formatolivro(
idFormato int auto_increment,
descricao_for varchar(20),
primary key (idFormato)
);
/*INSERT FORMATO_LIVRO*/
INSERT INTO formatolivro(descricao_for)  VALUES ('CAPA DURA');
INSERT INTO formatolivro(descricao_for) VALUES ('GRAMPO');
INSERT INTO formatolivro(descricao_for) VALUES ('BROCHURA');
INSERT INTO formatolivro(descricao_for) VALUES ('DIGITAL');
INSERT INTO formatolivro (descricao_for) VALUES ('ASPIRAL');

-- -----------------------------------------------------
-- Table `livrariabg`.`autor`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS autor (
  idAutor INT AUTO_INCREMENT,
  nomeAutor VARCHAR(100) NOT NULL,
  PRIMARY KEY (idAutor)
  );
   /*INSERT AUTOR*/
  INSERT INTO AUTOR (nomeAutor) VALUES ('JOSE SABINO');
  INSERT INTO AUTOR (nomeAutor) VALUES ('MARIA DAS DORES');
  INSERT INTO AUTOR (nomeAutor) VALUES ('ANTONIO ARMINIO');
  INSERT INTO AUTOR (nomeAutor) VALUES ('CARLOS EDUARDO');
  INSERT INTO AUTOR (nomeAutor) VALUES ('VILMA DE OLIVEIRA');
  INSERT INTO AUTOR (nomeAutor) VALUES ('ANA MARIA');

  select * from AUTOR;
-- -----------------------------------------------------
-- Table `livrariabg`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categoria (
  idCategoria INT NOT NULL AUTO_INCREMENT,
  nomeCategoria VARCHAR(100) NOT NULL,
  PRIMARY KEY (idCategoria)
  );
   /*INSERT CATEGORIA */
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('ADMINISTRAÇÃO');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('ARTES');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('AUTOAJUDA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('CIÊNCIAS BIOLÓGICAS');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('CIÊNCIAS EXATAS');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('CIÊNCIAS HUMANAS E SOCIAIS');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('DIDÁTICOS');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('DIREITO');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('DIVERSOS');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('ECONOMIA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('ESOTERISMO');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('ESPORTES E LAZER');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('GEOGRAFIA E HISTORIA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('INFORMÁTICA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('LINGUÍSTICA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('LITERATURA BRASILEIRA	');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('LITERATURA ESTRANGEIRA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('MEDICINA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('PSICOLOGIA E PSICANÁLISE');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('RELIGIÃO');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('FICÇÃO CIENTÍFICA FANTASIA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('BIOGRAFIA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('AVENTURA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('FANTASIA');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('INFANTO JUVENIL');
INSERT INTO CATEGORIA(nomeCategoria) VALUES ('INFANTO JUVENIL');

SELECT * FROM CATEGORIA;

-- -----------------------------------------------------
-- Table `Livrariabg`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS livro (
  idLivro INT NOT NULL AUTO_INCREMENT,
  idFormato INT,
  idEditora INT,
  idAutor INT,
  idCategoria INT,
  isbn char(15),
  titulo VARCHAR(100) NOT NULL, 
  descricao VARCHAR(250),
  capaLivro VARCHAR(45),
  paginas INT NULL,
  estoque INT NULL,
  valorUnit numeric(10,2),
  dataLanc date,
 PRIMARY KEY (idLivro),
 FOREIGN KEY (idEditora) REFERENCES editora (idEditora),
 FOREIGN KEY (idFormato) REFERENCES formatolivro (idFormato),
 FOREIGN KEY (idAutor) REFERENCES autor (idAutor),
 FOREIGN KEY (idCategoria) REFERENCES categoria (idCategoria)
);
select * from livro;

INSERT INTO LIVRO(idFormato, idEditora,idAutor, idCategoria, isbn, titulo, descricao, capaLivro, paginas,
 estoque, valorUnit, dataLanc) 
VALUES (1, 13, 1, 1, '8533613377', 'O SENHOR DOS ANÉIS I - A SOCIEDADE DO ANEL', 
'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que
precisa ser destruído antes que caia nas mãos do mal',
'', 600, 50, 44.00, '2000/02/03'
);
INSERT INTO LIVRO(idFormato, idEditora,idAutor, idCategoria, isbn, titulo, descricao, capaLivro, paginas, 
estoque, valorUnit, dataLanc)
VALUES (1,14,2,5,'9788582714225', 'BIOLOGIA MOLECULAR DA CÉLULA - 6ª ED. 2017',
 'De modo mais específico, a Biologia Molecular busca compreender os mecanismos de
 replicação, transcrição e tradução do material genético,',
'', 1000, 75,  342.90,'2017/01/01'
);
INSERT INTO LIVRO(idFormato, idEditora,idAutor, idCategoria, isbn, titulo, descricao, capaLivro, paginas,
 estoque, valorUnit, dataLanc) 
 VALUES( 1, 1, 5, 2, '9788580572186', 'CINQUENTA TONS DE CINZA',
'A estudante de literatura Anastasia Steele, de 21 anos, entrevista o jovem bilionário Christian Grey, como um favor a sua colega de quarto Kate Kavanagh.',
'', 800, 30,  29.90 ,'2011/06/20'
);

/* LIvros ainda não inserido 
INSERT INTO LIVRO
VALUES (
'9788562409882', 
'A GAROTA DO LAGO',
'uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.',
3,
15,
'2017/01/04',
8.00,
11.90);

INSERT INTO LIVRO 
VALUES (
'9788593156755',
'A ORAÇÃO DE SÃO FRANCISCO',
'É a chamada Oração de São Francisco de Assis, um pequeno texto cheio de boas ideias.',
4,
11,
'2018/11/01',
30.00,
34.90);

INSERT INTO LIVRO
VALUES
(9788504019742,
'O RETORNO DE SHERLOCK HOLMES',
'Ressuscitou Sherlock Holmes, após contar sua morte na cena famosa em que desaparece nas cataratas de Reichenbach...',
1,
5,
'2015/03/25',
29.99,
39.90);

INSERT INTO LIVRO
 VALUES 
 ('9788569514732', 
 'ESTRELAS ALÉM DO TEMPO ',
 'No auge da corrida espacial travada entre Estados Unidos e Rússia durante a Guerra Fria, uma equipe de cientistas da NASA...',
 1,
 16,
 '2017/01/16'
 ,22.90,
 23.30);

INSERT INTO LIVRO 
VALUES 
('9788575426234',
'JOGANDO PARA VENCER ',
'coleção esportiva de lições de liderança organizados pelo então treinador da seleção brasileira masculina de vôlei Bernardinho...',
3,
3,
'2011/01/20',
29.90,
19.99);

INSERT INTO LIVRO
 VALUES 
 ('9788555390494', 
 'AS MELHORES HISTÓRIAS DE VIAGEM NO TEMPO',
 '...dezoito contos de alguns dos gigantes do universo sci-fi, abrangendo cinco década...',
  2,
 20,
 '2016/09/14',
 54.90,
 36.90);
  
INSERT INTO LIVRO 
VALUES 
('9788593911224',
 'E SE EU FOSSE PURA',
 'Amara mostra a vida por trás dos panos da profissão mais malfalada do mundo, mostrando as angústias, os medos, os preconceitos...',
3,
10,
'2016/02/05',
20.90,
39.39);
 
INSERT INTO LIVRO
VALUES (
'9788576831303',
'DIARIO DE UM BANANA',
'um garoto da sexta série que não tem muitos amigos, não é muito popular...',
1,
22,
'2007/04/01',
22.90,
30.90);

INSERT INTO LIVRO
VALUES (
'9788533613393',
'SENHOR DOS ANÉIS: O RETORNO DO REI',
'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima.',
3,
10,
'1955/07/29',
60.45,
90.80);

INSERT INTO LIVRO
VALUES 
('9788553611218',
'CLT – CONSOLIDAÇÃO DAS LEIS DO TRABALHO',
'A CLT surgiu pelo Decreto-Lei nº 5.452, de 1 de maio de 1943, sancionada pelo então presidente Getúlio Vargas',
4,
20,
'2019/03/21',
110.00,
220.00
);
INSERT INTO LIVRO
VALUES (
'9788576849209',
'REGRAS DO JOGO',
'Mateus é um garoto pobre, afrodescendente, abandonado pelo pai ver- dadeiro e rejeitado pelo pai adotivo... ',
4,
21,
'2015/08/08',
20.50,
40.90
);
*/

-- -----------------------------------------------------
-- Table `Livrariabg`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS produto (
  idProduto INT NOT NULL AUTO_INCREMENT,
  idCategoria INT NOT NULL,
  nomeProd VARCHAR(100) NOT NULL,
  marcaProd VARCHAR(45) NOT NULL,
  quantidade INT NOT NULL,
  preco DOUBLE NOT NULL,
  PRIMARY KEY (idProduto),
  FOREIGN KEY (idCategoria) REFERENCES categoria (idCategoria)
   );
  insert into produto(idCategoria, nomeProd, marcaProd, quantidade, preco) 
  VALUES(14, 'Teclado sem fio', 'Exbom', 100, 15.00);
  insert into produto(idCategoria, nomeProd, marcaProd, quantidade, preco) 
  VALUES(9, 'Caneta', 'Bic', 300, 5.00);
  
  select * from produto
  inner join categoria on categoria.idCategoria = produto.idCategoria;

select * from categoria;
-- -----------------------------------------------------
-- Table `livrariabg`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS pagamento (
  idPagamento INT NOT NULL AUTO_INCREMENT,
  FormaPag VARCHAR(45)NOT NULL,
  ModalPag VARCHAR(100),
  numParcela VARCHAR(100),
  PRIMARY KEY (idPagamento)
  );
  
  /*PAGAMENTO*/
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('DEBITO', 'A VISTA','');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Dinheiro', '','');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CRED A VISTA','');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CREDITO','PARC 2 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CREDITO','PARC 3 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CREDITO','PARC 4 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CREDITO','PARC 5 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (FormaPag, ModalPag, numParcela) VALUES ('Cartão', 'CREDITO','PARC 3 VEZES SEM JUROS');

-- -----------------------------------------------------
-- Table `livrariabg`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS entrega (
  idEntrega INT NOT NULL AUTO_INCREMENT,
  formaEntrega VARCHAR(50) NULL,
  PRIMARY KEY (idEntrega)
  );
  insert into entrega(formaEntrega)values('Moto-Boy');
  insert into entrega(formaEntrega)values('Retirar na loja');
  
  Select * from entrega;



-- -----------------------------------------------------
-- Table `livrariabg`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS pedido (
  idpedido INT NOT NULL AUTO_INCREMENT,
  idFunc INT NULL,
  idCliente INT NULL,
  idLivro INT NULL,
  idProduto INT NULL,
  idPagamento INT NULL,
  idEntrega INT NULL,
  quantidade INT NULL,
  statusPedido VARCHAR(45),
  valorTotal numeric(10,2),
  dataPedido DATE,
  dataEntrega DATE,
  PRIMARY KEY (idpedido),
  FOREIGN KEY (idFunc) REFERENCES funcionario (idFunc),
  FOREIGN KEY (idCliente) REFERENCES cliente(idCliente),
  FOREIGN KEY (idLivro) REFERENCES livro (idLivro),
  FOREIGN KEY (idProduto) REFERENCES produto (idProduto),
  FOREIGN KEY (idPagamento) REFERENCES pagamento (idPagamento),
  FOREIGN KEY (idEntrega) REFERENCES entrega (idEntrega)
 );

-- -----------------------------------------------------
-- Table `mydb`.`itensPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS itensPedido (
  idItensPedido INT NOT NULL,
  idPedido INT,
  qtdade_item INT NULL,
  valorTotal DOUBLE NULL,
  status VARCHAR(45) NULL,
  PRIMARY KEY (`idItensPedido`),
  FOREIGN KEY (idPedido) REFERENCES pedido (idpedido)
  );